ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
baseurl = "/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Another R blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "ocean"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  customCSS = ["css/overrides.css"]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Because we need more R blogs"
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Philippe Massicotte"
  website = "PMassicotte.github.io"
  email = "pmassicotte@hotmail.com"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "pmassicotte"
  gitlab = "PMassicotte"
#  bitbucket = "username"
  twitter = "philmassicotte"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
  stackoverflow = "users/5558188/philippe-massicotte"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
  500px = "persican"

[[params.customCSS]]
     href = "css/overrides.css"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "page/publication/"
    weight = 3


[[menu.main]]
    name = "Presentations"
    url = "page/presentations/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
